/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.thiago.model.view;

import br.com.thiago.model.bean.Usuario;
import br.com.thiago.model.dao.UsuarioDAO;


/**
 *
 * @author Thiago César
 */
public class TelaLogin extends javax.swing.JFrame {

   Usuario objUser=new Usuario();
   UsuarioDAO checarDAO;
    
    
    public TelaLogin() {
        initComponents();
        
        /*if (conexao != null) {
            jlConexao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/bdConectado40x40.png")));
        } else {
            jlConexao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/BDdesconectado40x40.png")));
        }*/
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlUsuario = new javax.swing.JLabel();
        jlSenha = new javax.swing.JLabel();
        jlCadeadoLogin = new javax.swing.JLabel();
        jtUsuario = new javax.swing.JTextField();
        jPassSenha = new javax.swing.JPasswordField();
        jlConexao = new javax.swing.JLabel();
        jbtnLogar = new javax.swing.JButton();
        jbtnSair = new javax.swing.JButton();
        jlFundoLogin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jlUsuario.setFont(new java.awt.Font("Calisto MT", 1, 18)); // NOI18N
        jlUsuario.setForeground(new java.awt.Color(0, 102, 51));
        jlUsuario.setText("Usuário");
        getContentPane().add(jlUsuario);
        jlUsuario.setBounds(40, 60, 70, 30);

        jlSenha.setFont(new java.awt.Font("Calisto MT", 1, 18)); // NOI18N
        jlSenha.setForeground(new java.awt.Color(0, 102, 51));
        jlSenha.setText("Senha");
        getContentPane().add(jlSenha);
        jlSenha.setBounds(50, 120, 50, 22);

        jlCadeadoLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlCadeadoLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/thiago/model/image/Cadeado1.png"))); // NOI18N
        getContentPane().add(jlCadeadoLogin);
        jlCadeadoLogin.setBounds(310, 40, 180, 220);

        jtUsuario.setFont(new java.awt.Font("Calisto MT", 1, 18)); // NOI18N
        getContentPane().add(jtUsuario);
        jtUsuario.setBounds(110, 60, 170, 28);

        jPassSenha.setFont(new java.awt.Font("Calisto MT", 1, 18)); // NOI18N
        getContentPane().add(jPassSenha);
        jPassSenha.setBounds(110, 120, 170, 28);
        getContentPane().add(jlConexao);
        jlConexao.setBounds(10, 240, 50, 50);

        jbtnLogar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbtnLogar.setText("Logar");
        jbtnLogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnLogarActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnLogar);
        jbtnLogar.setBounds(80, 220, 80, 25);

        jbtnSair.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbtnSair.setText("Sair");
        jbtnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSairActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnSair);
        jbtnSair.setBounds(190, 220, 80, 25);

        jlFundoLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/thiago/model/image/Tela_login_verde_500x300.jpg"))); // NOI18N
        getContentPane().add(jlFundoLogin);
        jlFundoLogin.setBounds(0, 0, 500, 300);

        setSize(new java.awt.Dimension(500, 300));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jbtnSairActionPerformed

    private void jbtnLogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLogarActionPerformed

            /*objUser.setLogin_Usuario(jtUsuario.getText());
            objUser.setSenha_Usuario(jPassSenha.getText());
            checarDAO.save(objUser);*/
            
            //objUser = checarDAO.consultarUsuario(objUser.getLogin_Usuario(), objUser.getSenha_Usuario());
		
		
            

    }//GEN-LAST:event_jbtnLogarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField jPassSenha;
    private javax.swing.JButton jbtnLogar;
    private javax.swing.JButton jbtnSair;
    private javax.swing.JLabel jlCadeadoLogin;
    private javax.swing.JLabel jlConexao;
    private javax.swing.JLabel jlFundoLogin;
    private javax.swing.JLabel jlSenha;
    private javax.swing.JLabel jlUsuario;
    private javax.swing.JTextField jtUsuario;
    // End of variables declaration//GEN-END:variables
}
